//! Phase-conditioned speculative decoding — the bridge between Meridian's
//! entropy signals and a DSpark-class draft model.
//!
//! # Why this module exists
//!
//! DeepSpec, DeepSeek's open-source speculative-decoding toolkit, ships
//! ready-to-use draft models for the Qwen3 family. Its README states that
//! every released checkpoint was trained on data *generated by its
//! corresponding target model in non-thinking mode* — despite Qwen3 exposing
//! an explicit thinking/non-thinking toggle that production traffic uses.
//!
//! Meridian's existing thesis is that a reasoning request is two workloads
//! with different statistical properties. This module extends that thesis one
//! level down: if a drafter never saw thinking-mode text, its acceptance rate
//! against thinking-mode text should be measurably worse — which would make
//! speculative decoding's speedup **silently phase-dependent** for anyone
//! using these checkpoints as shipped.
//!
//! # What is and is not claimed here
//!
//! | Status | Statement |
//! |---|---|
//! | **Verified** | DeepSpec's released Qwen3 drafters were trained on non-thinking-mode generations (its README says so). |
//! | **Proved** | Meridian's EAT signal *is* the DSpark confidence head's supervision target for a specific drafter, and target entropy ceilings the acceptance of any deterministic drafter. See [`confidence_model`]. |
//! | **Predicted, unmeasured** | Draft acceptance during the think phase is lower than during the output phase for these checkpoints. |
//!
//! The third row has not been measured, requires a GPU, and is not scheduled.
//! Nothing in this module reports a number that could be mistaken for it —
//! see [`provenance`] for the mechanism that keeps that true, and
//! [`hook::PhaseConditioningHook`] for the corresponding runtime posture: a
//! deployment with no measurement in hand can only ever draft *less*, never
//! more.
//!
//! # Layout
//!
//! - [`confidence_model`] — **MER-P0.1/P0.2/P0.3**. What DSpark's confidence
//!   head computes, what Meridian's EAT/RPDI signal computes, and the four
//!   propositions relating them, each with tests.
//! - [`hook`] — **MER-P0.5**. The scheduler-facing interface: phase label plus
//!   entropy sample in, recommended draft parameters out.
//! - [`ledger`] — phase-segmented acceptance accounting and the Section 5 test
//!   statistic. Empty until Phase 1 supplies data; ready the moment it does.
//! - [`provenance`] — the type-level gate separating synthetic traces from
//!   measurements.
//! - [`stats`] — Welch's unequal-variance _t_-test and the supporting
//!   distribution functions.
//!
//! # End-to-end shape
//!
//! ```
//! use meridian_core::dspark_bridge::{
//!     AcceptanceLedger, AcceptanceObservation, PhaseConditioningConfig,
//!     PhaseConditioningHook, Provenance, SpeculationPhase,
//! };
//!
//! // 1. Serving side: consult the hook per request per step.
//! let hook = PhaseConditioningHook::new(PhaseConditioningConfig::default())?;
//! let policy = hook.policy_for(SpeculationPhase::Think, None);
//! assert!(!hook.is_calibrated()); // ... and stays that way until Phase 1 runs.
//!
//! // 2. Offline side: fold harness output into a phase-segmented ledger.
//! let mut ledger = AcceptanceLedger::new(Provenance::synthetic("readme-example"));
//! ledger.record(&AcceptanceObservation::new(
//!     SpeculationPhase::Think,
//!     3,
//!     policy.proposal_len,
//! ));
//!
//! // 3. Synthetic data can be analysed, but never promoted to a claim.
//! assert!(ledger.report().into_measured_claim().is_err());
//! # Ok::<(), meridian_core::Error>(())
//! ```
//!
//! # References
//!
//! - Cheng et al., *DSpark: Confidence-Scheduled Speculative Decoding with
//!   Semi-Autoregressive Generation*, DeepSeek-AI and Peking University
//!   ([arXiv:2607.05147](https://arxiv.org/abs/2607.05147)).
//! - [`deepseek-ai/DeepSpec`](https://github.com/deepseek-ai/DeepSpec) — MIT
//!   licensed; third-party adapted code is attributed in its `NOTICE`.
//! - [ADR-0009](https://github.com/angelnicolasc/meridian/blob/main/docs/src/adr/0009-phase-conditioned-speculation.md)
//!   — why the hook ships inert.

pub mod confidence_model;
pub mod hook;
pub mod ledger;
pub mod provenance;
pub mod stats;

pub use crate::dspark_bridge::confidence_model::{
    AcceptanceBounds, acceptance_of_point_mass_draft, analytical_acceptance,
    boundary_drafter_acceptance_ceiling, deterministic_acceptance_ceiling, eat_as_acceptance_rate,
    expected_accepted_length, mode_mass_lower_bound, prefix_survival, total_variation,
};
pub use crate::dspark_bridge::hook::{
    AcceptancePrior, DraftCostModel, DraftPolicy, PhaseConditioningConfig, PhaseConditioningHook,
    PolicyBasis, SpeculationPhase,
};
pub use crate::dspark_bridge::ledger::{
    AcceptanceLedger, AcceptanceObservation, HypothesisVerdict, MeasuredPhaseGap, PhaseGapReport,
    PhaseStats, StraddlePolicy,
};
pub use crate::dspark_bridge::provenance::{MeasuredRun, Provenance};
pub use crate::dspark_bridge::stats::{Moments, WelchResult, welch_t_test};
