//! Provenance tagging — the mechanism that keeps §11 of the blueprint's
//! publication rule enforceable by the compiler rather than by discipline.
//!
//! The phase-conditioned-speculation work has one non-negotiable rule: the
//! verified fact (DeepSpec's released Qwen3 drafters were trained on
//! non-thinking-mode generations) and the prediction (draft acceptance is
//! therefore phase-dependent) must stay visibly separated, and **no number
//! produced before a GPU run may be presented as a measurement**.
//!
//! Rules enforced by prose get broken. So every acceptance statistic in this
//! module tree carries a [`Provenance`], every report renders it, and the one
//! function that produces a publication-ready claim —
//! [`Provenance::into_measured`] — returns an error for anything synthetic.
//! A synthetic number cannot reach a paper without someone deleting code.

use std::fmt;

use serde::{Deserialize, Serialize};

use crate::error::{Error, Result};

/// Where a set of acceptance observations came from.
///
/// # Examples
///
/// ```
/// use meridian_core::dspark_bridge::Provenance;
///
/// let fixture = Provenance::synthetic("clean-phase-boundary");
/// assert!(!fixture.is_measurement());
/// assert!(fixture.into_measured().is_err());
/// ```
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum Provenance {
    /// Generated by a test fixture or a simulator. Never publishable as a
    /// measurement, whatever it looks like.
    Synthetic {
        /// Name of the fixture that produced the trace, for traceability from
        /// a report back to the code that generated it.
        fixture: String,
    },

    /// Recorded from a real speculative-decoding run against real models.
    Measured {
        /// Evaluation harness and version, e.g. `"DeepSpec@<sha>"`.
        harness: String,
        /// Draft checkpoint under test, e.g. `"deepseek-ai/dspark_qwen3_4b_block7"`.
        draft_checkpoint: String,
        /// Target model, e.g. `"Qwen/Qwen3-4B"`.
        target_model: String,
        /// Whether the target ran with the thinking-mode toggle enabled. The
        /// entire hypothesis is a comparison across this flag, so a trace that
        /// does not record it is not interpretable.
        thinking_mode: bool,
        /// ISO-8601 date the run was recorded.
        recorded_on: String,
    },
}

impl Provenance {
    /// Tag a trace as synthetic.
    #[must_use]
    pub fn synthetic(fixture: impl Into<String>) -> Self {
        Self::Synthetic {
            fixture: fixture.into(),
        }
    }

    /// `true` only for [`Provenance::Measured`].
    #[must_use]
    pub const fn is_measurement(&self) -> bool {
        matches!(self, Self::Measured { .. })
    }

    /// Stable telemetry label (`"synthetic"` / `"measured"`).
    #[must_use]
    pub const fn as_label(&self) -> &'static str {
        match self {
            Self::Synthetic { .. } => "synthetic",
            Self::Measured { .. } => "measured",
        }
    }

    /// The banner every rendered report opens with. Loud for synthetic data,
    /// descriptive for real data.
    #[must_use]
    pub fn banner(&self) -> String {
        match self {
            Self::Synthetic { fixture } => {
                format!(
                    "SYNTHETIC TRACE ({fixture}) — NOT A MEASUREMENT. Do not publish as a result."
                )
            }
            Self::Measured {
                harness,
                draft_checkpoint,
                target_model,
                thinking_mode,
                recorded_on,
            } => {
                let mode = if *thinking_mode {
                    "thinking-mode ON"
                } else {
                    "thinking-mode OFF"
                };
                format!(
                    "MEASURED — {harness} · {draft_checkpoint} vs {target_model} · {mode} · {recorded_on}"
                )
            }
        }
    }

    /// Consume this provenance and return the measured description, or fail.
    ///
    /// The only supported path from a statistic to a published claim. Calling
    /// it on synthetic data is an error, not a warning.
    ///
    /// # Errors
    ///
    /// [`Error::SyntheticProvenance`] if this is [`Provenance::Synthetic`].
    pub fn into_measured(self) -> Result<MeasuredRun> {
        match self {
            Self::Measured {
                harness,
                draft_checkpoint,
                target_model,
                thinking_mode,
                recorded_on,
            } => Ok(MeasuredRun {
                harness,
                draft_checkpoint,
                target_model,
                thinking_mode,
                recorded_on,
            }),
            Self::Synthetic { fixture } => Err(Error::SyntheticProvenance { fixture }),
        }
    }
}

impl fmt::Display for Provenance {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.banner())
    }
}

/// A provenance that has been proven to describe a real run.
///
/// Only obtainable through [`Provenance::into_measured`], so a value of this
/// type is evidence that the numbers accompanying it came from hardware.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct MeasuredRun {
    /// Evaluation harness and version.
    pub harness: String,
    /// Draft checkpoint under test.
    pub draft_checkpoint: String,
    /// Target model.
    pub target_model: String,
    /// Whether the target ran with thinking mode enabled.
    pub thinking_mode: bool,
    /// ISO-8601 date the run was recorded.
    pub recorded_on: String,
}

#[cfg(test)]
mod tests {
    use super::*;

    fn measured() -> Provenance {
        Provenance::Measured {
            harness: "DeepSpec@0000000".into(),
            draft_checkpoint: "deepseek-ai/dspark_qwen3_4b_block7".into(),
            target_model: "Qwen/Qwen3-4B".into(),
            thinking_mode: true,
            recorded_on: "2026-08-07".into(),
        }
    }

    #[test]
    fn synthetic_can_never_become_a_measured_claim() {
        let p = Provenance::synthetic("all-think");
        assert!(!p.is_measurement());
        assert_eq!(p.as_label(), "synthetic");
        let err = p.into_measured().unwrap_err();
        assert!(matches!(err, Error::SyntheticProvenance { .. }));
    }

    #[test]
    fn measured_converts_and_preserves_every_field() {
        let p = measured();
        assert!(p.is_measurement());
        assert_eq!(p.as_label(), "measured");
        let run = p.into_measured().unwrap();
        assert_eq!(run.target_model, "Qwen/Qwen3-4B");
        assert!(run.thinking_mode);
        assert_eq!(run.recorded_on, "2026-08-07");
    }

    #[test]
    fn synthetic_banner_is_unmissable() {
        let banner = Provenance::synthetic("ambiguous-boundary").banner();
        assert!(banner.contains("SYNTHETIC"));
        assert!(banner.contains("NOT A MEASUREMENT"));
        assert!(banner.contains("ambiguous-boundary"));
    }

    #[test]
    fn measured_banner_records_the_thinking_mode_flag_in_both_states() {
        assert!(measured().banner().contains("thinking-mode ON"));

        let off = Provenance::Measured {
            harness: "DeepSpec@0000000".into(),
            draft_checkpoint: "deepseek-ai/dspark_qwen3_4b_block7".into(),
            target_model: "Qwen/Qwen3-4B".into(),
            thinking_mode: false,
            recorded_on: "2026-08-07".into(),
        };
        assert!(off.banner().contains("thinking-mode OFF"));
    }

    #[test]
    fn round_trips_through_toml() {
        let toml_text = r#"
            kind = "measured"
            harness = "DeepSpec@deadbeef"
            draft_checkpoint = "deepseek-ai/dspark_qwen3_8b_block7"
            target_model = "Qwen/Qwen3-8B"
            thinking_mode = true
            recorded_on = "2026-08-07"
        "#;
        let parsed: Provenance = toml::from_str(toml_text).unwrap();
        assert!(parsed.is_measurement());

        let synthetic: Provenance = toml::from_str(
            r#"
            kind = "synthetic"
            fixture = "degenerate-all-output"
        "#,
        )
        .unwrap();
        assert!(!synthetic.is_measurement());
    }

    #[test]
    fn display_matches_banner() {
        let p = Provenance::synthetic("fixture-x");
        assert_eq!(p.to_string(), p.banner());
    }
}
